name: Comment on New Issues
on:
  issues:
    types:
      - opened

jobs:
  add-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Render Comment Template
        id: template
        uses: chuhlomin/render-template@v1.4
        with:
          template: .github/issue-comment-template.md
          vars: |
            user: ${{ github.event.issue.user.login }}
            userLink: ${{ github.event.issue.user.html_url }}
            repo: ${{ github.repository }}

      - name: Add Comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: ${{ steps.template.outputs.result }}
